name: AI Code Analysis

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: registry.cn-shenzhen.aliyuncs.com/runcobo/ai-code-stats:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}  # 直接从 Repository secrets 读取
        password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 必须获取前一个提交用于diff分析
