name: AI Code Analysis

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：登录阿里云容器镜像服务
      - name: Login to Alibaba Cloud ACR
        run: |
          docker login \
            -u ${{ secrets.ACR_USERNAME }} \
            -p ${{ secrets.ACR_PASSWORD }} \
            registry.cn-shenzhen.aliyuncs.com

      # 步骤2：运行分析容器
      - name: Run Analysis
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/code \
            -w /code \
            registry.cn-shenzhen.aliyuncs.com/runcobo/ai-code-stats:latest
